### ISSUE TITLE
Buen trabajo!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-martagrio#1]
Buen trabajo @martagrio  !

Algunas pistas para mejorarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Publica en Github Pages

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by martagrio** [comment]
Thanks for the tips. I have updated both branches and published it on GitHub pages with all the improvements done. If I can I will update once again with the favs feature.

**Comment by oneeyedman** [comment]
Las PropTypes no están del todo correctas y sigues usando el index del map para pintar la lista de pokemons, en lugar de usar el id de los datos.

**Comment by martagrio** [comment]
Thanks again! I removed the index in map and set both id and key values as each pokemon id. I think I fixed the errors in the PropTypes too but please let me know if there is still anything set incorrectly.

**Comment by martagrio** [comment]
After checking with you, both PropTypes and id issues are fixed. Thanks!
